### PR TITLE
Bump sdl2_ttf to 2.0.15

### PR DESCRIPTION
**Pull request by matham**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matham** [comment]
@conda-forge-admin, please rerender

**Comment by matham** [comment]
This seems to be failing specifically on `win_c_compilervs2008`. The error is:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6 -> vc[version='>=14,<15.0a0']
  - vc=9
```

It seems that it's trying to install python 3.6: `python                    3.6.5                h0c2934d_0    defaults`. I don't understand how this is possible. Shouldn't the vs2008 only be tested on 2.7? Why is it trying to install 3.6?

**Comment by matham** [comment]
All tests have finally passed. This should be merged after https://github.com/conda-forge/sdl2-feedstock/pull/12 is merged and the package is uploaded.

**Comment by dschreij** [comment]
Thanks @matham

**Pull request merged**
